version: '3'

services:
  agent:
    build:
      context: ../
      dockerfile: agent/Dockerfile
    environment:
      REDIS: redis:6379
    volumes:
      - ../../work/agent/data:/data
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    cap_add:
      - SYS_RESOURCE
