// <auto-generated>

namespace Safir.ControlLibrary.Native
{
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
    internal class MONITORINFO
    {
        public int CbSize = Marshal.SizeOf(typeof(MONITORINFO));
        public RECT RcMonitor = default(RECT);
        public RECT RcWork = default(RECT);
        public int DwFlags = 0;

        public enum MonitorOptions : uint
        {
            MONITOR_DEFAULTTONULL = 0x00000000,
            MONITOR_DEFAULTTOPRIMARY = 0x00000001,
            MONITOR_DEFAULTTONEAREST = 0x00000002
        }
    }
}
