name: PR
on:
  pull_request:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  CI: true
jobs:
  dotnet_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    - name: Add github source credentials
      run: |
        dotnet nuget update source \
          github \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text
        
    - name: Restore dependencies
      run: dotnet restore --nologo
      
    - name: Build solution
      run: dotnet build --no-restore --nologo
      
    - name: Run tests
      run: dotnet test --no-build --verbosity normal --nologo

  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: |
        docker build . --file Dockerfile \
          --build-arg GithubUsername=${{ github.actor }} \
          --build-arg GithubPassword=${{ secrets.GITHUB_TOKEN }} \
          --tag safir-manager:$(date +%s)
