name: CLI PR
on:
  pull_request:
    paths:
    - src/cli/**
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  CI: true
jobs:
  dotnet_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/cli

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore --locked-mode --nologo

    - name: Build solution
      run: dotnet build --no-restore --nologo

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --nologo

  docker_build:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: localhost:5000/safir/cli-base
    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000
    steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build base image
      id: base-build
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:src"
        file: ./common/dotnet/Dockerfile
        push: true
        tags: ${{ env.BASE_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:src"
        file: ./cli/Dockerfile
        build-args: CommonImage=${{ env.BASE_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
