name: Common .NET PR
on:
  pull_request:
    paths:
    - src/common/dotnet/**
    - src/protos/**
env:
  CI: true
jobs:
  dotnet_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/common/dotnet

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  docker_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build base image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./common/dotnet/Dockerfile
        tags: safir-common-dotnet
        cache-from: type=registry,ref=${{ env.REPOSITORY }}:buildcache
        cache-to: type=registry,ref=${{ env.REPOSITORY }}:buildcache,mode=max
      env:
        REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}/safir-common-dotnet
