name: Common .NET Pull Request
on:
  pull_request:
    paths:
    - protos/**
    - src/common/src/dotnet/**
env:
  CI: true
jobs:
  dotnet_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/common/src/dotnet

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
