name: Docker Publish
on:
  push:
    branches: [main]
    tags: [v*]
    paths:
    - "src/Safir.Agent/**"
env:
  IMAGE_NAME: safir-agent
jobs:
  docker_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build and push
      run: |
        GITHUB_IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
        DOCKERHUB_IMAGE_ID=unstoppablemango/$IMAGE_NAME
        
        dotnet tool restore && VERSION=$(dotnet minver -t v)
        docker build . --file Dockerfile  \
          --build-arg GithubUsername=${{ github.actor }} \
          --build-arg GithubPassword=${{ secrets.GITHUB_TOKEN }} \
          --tag $IMAGE_NAME:latest \
          --tag $IMAGE_NAME:$VERSION \
          --tag $GITHUB_IMAGE_ID:latest \
          --tag $GITHUB_IMAGE_ID:$VERSION \
          --tag $DOCKERHUB_IMAGE_ID:latest \
          --tag $DOCKERHUB_IMAGE_ID:$VERSION

        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u unstoppablemango --password-stdin
        
        docker push $GITHUB_IMAGE_ID --all-tags
        docker push $DOCKERHUB_IMAGE_ID --all-tags
