name: NuGet Publish
on:
  push:
    branches: [main]
    tags: ["*.*.*"]
    paths:
    - "src/dotnet/Directory.build.*"
    - "src/dotnet/src/**"
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  CI: true
jobs:
  dotnet_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/dotnet
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Add github source credentials
      run: |
        dotnet nuget update source \
          github \
          --username UnstoppableMango \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text

    - name: Build solution
      run: dotnet build --configuration Release --nologo

    - name: Run tests
      run: dotnet test --configuration Release --no-build --nologo

    - name: Package libraries
      run: dotnet pack --configuration Release --no-build --nologo

    - name: Push packages to Github
      run: |
        dotnet nuget push src/**/*.nupkg \
          --source https://nuget.pkg.github.com/unmango/index.json \
          --api-key ${{ secrets.GITHUB_TOKEN }}
