name: UI PR
on:
  pull_request:
    paths:
      - src/common/node/**
      - src/protos/**
      - src/ui/**
env:
  CI: true
jobs:
  yarn_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14
          cache: yarn

      - name: Restore dependencies
        run: yarn install --immutable --check-cache

      - name: Run tests
        run: yarn test

      - name: Build app
        run: yarn build

  docker_build:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: localhost:5000/safir/ui-base
    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build base image
        id: base-build
        uses: docker/build-push-action@v2
        with:
          file: ./src/common/node/Dockerfile
          push: true
          tags: ${{ env.BASE_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: ./src/ui/Dockerfile
          build-args: BaseImage=${{ env.BASE_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
