name: UI PR
on:
  pull_request:
    paths:
      - src/common/node/**
      - src/protos/**
      - src/ui/**
env:
  CI: true
jobs:
  yarn_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Restore dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Build app
        run: yarn build

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          file: ./src/common/node/Dockerfile
          load: true
          tags: safir-common-node
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: ./src/ui/Dockerfile
          build-args: BaseImage=safir-common-node
          cache-from: type=gha
          cache-to: type=gha,mode=max
